In [3]:
import torch 

---
# 초기값 생성 방법
---

In [6]:
x = torch.empty(size = (3,3))
# x = torch.empty(3,3)
print(x)

tensor([[6.5007e-35, 0.0000e+00, 1.5975e-43],
        [1.3873e-43, 1.4574e-43, 6.4460e-44],
        [1.4153e-43, 1.5274e-43, 1.5695e-43]])


In [8]:
x = torch.zeros(3,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [9]:
x = torch.rand(3,3)
print(x)

tensor([[0.3134, 0.5106, 0.8184],
        [0.5316, 0.5478, 0.4112],
        [0.0252, 0.1649, 0.2319]])


In [10]:
x = torch.ones(3,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [11]:
x = torch.eye(5,5)
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [20]:
x = torch.arange(start=0 , end=5 , step=1)
# x = torch.arange(0,5,1)
print(x)

tensor([0, 1, 2, 3, 4])


In [24]:
x = torch.linspace(start=0.1 , end=1 , steps=10)
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [26]:
# 빈 값을 평균이 0 표준 편차가 1인 값으로 생성
x = torch.empty(size = (1,5)).normal_(mean = 0, std = 1)
print(x)

tensor([[ 0.7610, -0.3529, -0.6275,  1.3715,  0.1453]])


In [29]:
# rand와 동일한 작업이지만, 균일 분포에 의해 상한과 하한의 값을 정해 놓는것
x = torch.empty(size = (1,5)).uniform_(0,1)
print(x)

tensor([[0.0067, 0.7817, 0.0204, 0.2034, 0.1045]])


In [31]:
# 대각행렬
x = torch.diag(torch.ones(3))
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


---
# 텐서를 다른 유형으로 초기화 및 변환
---

In [39]:
tensor = torch.arange(4)
print(tensor.bool(),'\n')
print(tensor.short(),'\n') # int16
print(tensor.long(),'\n') # int64
print(tensor.half(),'\n') # float16
print(tensor.float(),'\n') # float32
print(tensor.double(),'\n') # float64

tensor([False,  True,  True,  True]) 

tensor([0, 1, 2, 3], dtype=torch.int16) 

tensor([0, 1, 2, 3]) 

tensor([0., 1., 2., 3.], dtype=torch.float16) 

tensor([0., 1., 2., 3.]) 

tensor([0., 1., 2., 3.], dtype=torch.float64) 



---
# 텐서간의 변환(array to tensor)
---

In [40]:
import numpy as np

In [48]:
np_array = np.zeros((5,5))
print(np_array, '\n')

# 텐서로 변환
tensor = torch.from_numpy(np_array)
print(tensor, '\n')

# 되돌리기
np_array_back = tensor.numpy()
print(np_array_back, '\n')

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64) 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 



---
# 텐서 수학 및 비교 연산
---

In [49]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

In [52]:
# 덧셈
z1 = torch.empty(3)
torch.add(x, y, out = z1)
print(z1,'\n')

z2 = torch.add(x,y)
print(z2,'\n')

z = x + y 
print(z,'\n')

tensor([10., 10., 10.]) 

tensor([10, 10, 10]) 

tensor([10, 10, 10]) 



In [53]:
# 뺄셈
z = x - y
print(z,'\n')

tensor([-8, -6, -4]) 



In [54]:
# 나누기
z = torch.true_divide(x,y)
print(z,'\n')

tensor([0.1111, 0.2500, 0.4286]) 



In [58]:
# inplace operations
t = torch.zeros(3)
t.add_(x)
# t += x
print(t,'\n')

tensor([1., 2., 3.]) 



In [59]:
# 지수화
z = x.pow(2)
# z = x **2
print(z)

tensor([1, 4, 9])


In [61]:
z = x > 0
print(z)

z = x < 0
print(z)

tensor([True, True, True])
tensor([False, False, False])


In [65]:
# 행렬의 곱셈
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))

x3 = torch.mm(x1,x2) 
# x3 = x1.mm(x2)
print(x3.shape)

torch.Size([2, 3])


In [66]:
# 행렬 지수화
matrix_exp = torch.rand(5,5)
print(matrix_exp.matrix_power(3))

tensor([[6.3981, 6.1353, 8.2452, 7.5626, 6.2937],
        [3.2346, 2.9835, 4.3107, 3.7656, 3.0455],
        [3.5067, 3.4867, 4.3403, 4.2268, 3.6320],
        [5.0620, 4.5763, 6.4947, 6.0998, 5.1252],
        [5.4957, 5.0678, 7.1432, 6.5157, 5.3936]])


In [68]:
z = x * y
print(z,'\n')

z = torch.dot(x,y)
print(z,'\n')

tensor([ 9, 16, 21]) 

tensor(46) 



In [73]:
# 배치 행렬 
batch = 32 
n = 10 
m = 20
p = 30

tensor1 = torch.rand((batch, n, m)) # 3차원 텐서
print(tensor1.shape, '\n')

tensor2 = torch.rand((batch, m, p))
print(tensor2.shape, '\n')

# 행렬 곱셈
out_bmm = torch.bmm(tensor1, tensor2) # (batch, n, p)
print(out_bmm.shape, '\n')

torch.Size([32, 10, 20]) 

torch.Size([32, 20, 30]) 

torch.Size([32, 10, 30]) 



---
# 브로드캐스팅 예시
---

In [76]:
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))

z = x1 - x2 
print(z.shape)

z = x1 ** x2
print(z.shape)

torch.Size([5, 5])
torch.Size([5, 5])


---
# 유용한 텐서 연산
---

In [89]:
# 합산해야 하는 차원을 지정
print(x, '\n')

# 합
sum_x = torch.sum(x, dim = 0)
print(sum_x, '\n')

# 가장 큰 값과 인덱스
values, index = torch.max(x, dim = 0)
print(values, index, '\n')

# 가장 작은 값과 인덱스
values, index = torch.min(x, dim = 0)
print(values, index, '\n')

# 절대값
abs_x = torch.abs(x)
print(abs_x,'\n')

tensor([1, 2, 3]) 

tensor(6) 

tensor(3) tensor(2) 

tensor(1) tensor(0) 

tensor([1, 2, 3]) 



In [90]:
# 최대값의 인덱스
z = torch.argmax(x, dim=0)
print(z,'\n')

# 최소값의 인덱스
z = torch.argmin(x, dim=0)
print(z,'\n')

# 평균
mean_x = torch.mean(x.float(), dim = 0)
print(mean_x,'\n')

# equal
z = torch.eq(x,y)
print(z)

tensor(2) 

tensor(0) 

tensor(2.) 

tensor([False, False, False])


In [94]:
sort, index = torch.sort(y, dim=0, descending = True)
print(sort, index)

tensor([9, 8, 7]) tensor([0, 1, 2])


In [102]:
# 0 보다 큰 x의 요소를 확인하고 최소값으로 변경
z = torch.clamp(x, min = 0)
print(z,'\n')

z = torch.clamp(x, min = 2)
print(z, '\n')

z = torch.clamp(x, max = 1)
print(z, '\n')

tensor([1, 2, 3]) 

tensor([2, 2, 3]) 

tensor([1, 1, 1]) 



In [112]:
x = torch.tensor([1,3,1,0,1], dtype = torch.bool)
print(x,'\n')

# 하나라도 True인가?
z = torch.any(x)
print(z,'\n')

# 모두 통일 되는가?
z = torch.all(x)
print(z,'\n')

tensor([ True,  True,  True, False,  True]) 

tensor(True) 

tensor(False) 



---
# 텐서의 인덱싱
---

In [121]:
batch_size = 10
features = 25

x = torch.rand((batch_size, features))
print(x.shape, '\n')
print(x[0].shape, '\n') # x[0,:]
print(x[:,0].shape, '\n')
print(x[2,0:15].shape, '\n')

torch.Size([10, 25]) 

torch.Size([25]) 

torch.Size([10]) 

torch.Size([15]) 



In [124]:
x = torch.arange(10,20)
index  = [2,5,7]

print(x[index])

tensor([12, 15, 17])


In [129]:
x = torch.rand((3,5))
rows = torch.tensor([1,2])
cols = torch.tensor([4,1])
print(x,'\n')
print(x[rows,cols]) # 2행 5열 / 3행 2열

tensor([[0.5937, 0.9651, 0.3329, 0.9112, 0.9959],
        [0.0702, 0.2838, 0.2125, 0.7493, 0.1960],
        [0.8677, 0.4660, 0.7101, 0.2649, 0.0524]]) 

tensor([0.1960, 0.4660])


In [134]:
x = torch.arange(10)
print(x[(x < 2) | (x > 8)])

# 짝수 요소
print(x[x.remainder(2) == 0 ])

# 홀수 요소
print(x[x.remainder(2) == 1 ])

tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])
tensor([1, 3, 5, 7, 9])


In [135]:
# x가 5보다 큰 요소를 먼저 찾고 
# 5보다 크다면 그대로
# 5보다 작다면 곱하기2
print(torch.where(x > 5, x, x*2))

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])


In [136]:
# 중복없는 고유의 값만 반환
print(torch.tensor([0,0,1,2,2,3,4,3,5]).unique())

tensor([0, 1, 2, 3, 4, 5])


In [137]:
# 몇 차원인가?
x.ndimension()

1

In [139]:
# 요소의 수
x.numel()

10

In [145]:
a = torch.tensor([[1,2],[2,4],[5,1]])
print(a.ndimension())
print(a.numel())

2
6


---
# reshape
----

In [151]:
x = torch.arange(9)
print(x,'\n')

x_33 = x.view(3,3)
print(x_33,'\n')

y = x_33.t()
print(y,'\n')

print(y.contiguous().view(9),'\n')

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]) 

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]) 

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]]) 

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8]) 



In [153]:
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))

print(torch.cat((x1,x2), dim=0).shape,'\n')
print(torch.cat((x1,x2), dim=1).shape,'\n')

torch.Size([4, 5]) 

torch.Size([2, 10]) 



In [155]:
z = x1.view(-1)
print(z.shape)

torch.Size([10])


In [156]:
batch = 64
x = torch.rand((batch, 2, 5, 5))
z = x.view(batch,-1)

print(x.shape,'\n')
print(z.shape,'\n')


torch.Size([64, 2, 5, 5]) 

torch.Size([64, 50]) 



In [159]:
z = x.permute(0,2,1,3)
print(z.shape)

torch.Size([64, 5, 2, 5])


In [163]:
x = torch.arange(10)

print(x.unsqueeze(0).shape,'\n')
print(x.unsqueeze(1).shape,'\n')

torch.Size([1, 10]) 

torch.Size([10, 1]) 



In [165]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)
print(x.shape,'\n')

z = x.squeeze(1)
print(z.shape,'\n')

torch.Size([1, 1, 10]) 

torch.Size([1, 10]) 

